//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje_Potrawy
    {
        public int id { get; set; }
        public int id_zamowienia { get; set; }
        public int id_potrawy { get; set; }
    
        public virtual Potrawy Potrawy { get; set; }
        public virtual Rezerwacje Rezerwacje { get; set; }
    }
}
