//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Restaurant
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rezerwacje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Rezerwacje()
        {
            this.Potrawy = new HashSet<Potrawy>();
        }
    
        public int Id_rezerwacji { get; set; }
        public int Id_klienta { get; set; }
        public int Numer_stolika { get; set; }
        public System.DateTime Rezerwacja_od { get; set; }
        public System.DateTime Rezerwacja_do { get; set; }
    
        public virtual Klienci Klienci { get; set; }
        public virtual Klienci Klienci1 { get; set; }
        public virtual Stoliki Stoliki { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Potrawy> Potrawy { get; set; }
    }
}
